# Generated by Django 4.0 on 2021-12-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211204_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('approved', 'approved'), ('unapproved', 'unapproved')], default='unapproved', max_length=100)),
            ],
        ),
    ]
